#!/bin/bash

PWD=`pwd`
GREP=/bin/grep
CUT=/usr/bin/cut
SED=/bin/sed
AWK=/usr/bin/awk
SORT=/bin/sort
HEAD=/usr/bin/head
TEE=/usr/bin/tee
RSCRIPT=/usr/bin/Rscript

HADOOP=/usr/bin/hadoop
tarfile=/data/EHC_1st.tar.gz

PIGZ=${PWD}/pigz-master/pigz
[ ! -f $PIGZ ] && ./pigzDownloadCompile.sh

$HADOOP fs -mkdir -p hdfs://master/tmp/Team48
$PIGZ -dc -p 4 ${tarfile} | tar -xf - -O | \
	$TEE >($HADOOP fs -put - hdfs://master/tmp/Team48/EHC_1st_round.log) \
	| $GREP -E '\] \"GET /action\?;act=order;uid=' - | \
        	$CUT -d ';' -f 4 | $CUT -d '=' -f 2 | \
        	$SED '/^$/d' | \
        	$AWK 'BEGIN {FS=","}{ 
                        for (i = 0; i < NF / 3; i++){ 
                                arr[$(i*3+1)] += int($(i*3+2)) * int($(i*3+3)) } } END {
                        for (i in arr){print i, arr[i]} }' | \
        	$SORT -k2 -n -r | \
        	$HEAD -n 20 | \
        	$AWK '{ printf "%02d,%s\n", NR, $1 }' | \
        	$RSCRIPT print.R > Team48_Result.txt

#cat Team48_Result.txt
#hadoop fs -ls hdfs://master/tmp/Team48

